// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajyerTakip;

namespace StajyerTakip.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190711085927_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StajyerTakip.Models.Birim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aciklama");

                    b.Property<string>("Ad");

                    b.HasKey("ID");

                    b.ToTable("Birim");
                });

            modelBuilder.Entity("StajyerTakip.Models.BirimKoordinatoru", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BirimID");

                    b.Property<int>("ModeratorID");

                    b.Property<int>("ProfilID");

                    b.HasKey("ID");

                    b.HasIndex("BirimID");

                    b.HasIndex("ModeratorID");

                    b.HasIndex("ProfilID");

                    b.ToTable("BirimKoordinatorleri");
                });

            modelBuilder.Entity("StajyerTakip.Models.Devamsizlik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BirimKoordinatoruID");

                    b.Property<int>("StajyerID");

                    b.Property<DateTime>("Tarih");

                    b.HasKey("ID");

                    b.HasIndex("BirimKoordinatoruID");

                    b.HasIndex("StajyerID");

                    b.ToTable("Devamsizlik");
                });

            modelBuilder.Entity("StajyerTakip.Models.EkDosya", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GunlukID");

                    b.Property<string>("Path");

                    b.HasKey("ID");

                    b.HasIndex("GunlukID");

                    b.ToTable("EkDosya");
                });

            modelBuilder.Entity("StajyerTakip.Models.Gunluk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Baslik");

                    b.Property<string>("Bilgiler");

                    b.Property<int?>("BirimKoordinatoruID");

                    b.Property<int>("OgrenciID");

                    b.Property<bool>("OnayDurumu");

                    b.Property<DateTime>("Tarih");

                    b.HasKey("ID");

                    b.HasIndex("BirimKoordinatoruID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("Gunluk");
                });

            modelBuilder.Entity("StajyerTakip.Models.Moderator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProfilID");

                    b.HasKey("ID");

                    b.HasIndex("ProfilID");

                    b.ToTable("Moderatorler");
                });

            modelBuilder.Entity("StajyerTakip.Models.Profil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("Adres");

                    b.Property<string>("Email");

                    b.Property<string>("Fotograf");

                    b.Property<string>("Il");

                    b.Property<string>("Ilce");

                    b.Property<string>("KullaniciAdi");

                    b.Property<int>("Rol");

                    b.Property<string>("Sifre");

                    b.Property<string>("Sokak");

                    b.Property<string>("Soyad");

                    b.Property<string>("Telefon");

                    b.HasKey("ID");

                    b.ToTable("Hesaplar");
                });

            modelBuilder.Entity("StajyerTakip.Models.Proje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("Icerik");

                    b.Property<string>("KullanilanTeknolojiler");

                    b.Property<int>("TanimlananSure");

                    b.HasKey("ID");

                    b.ToTable("Proje");
                });

            modelBuilder.Entity("StajyerTakip.Models.ProjeBirim", b =>
                {
                    b.Property<int>("ProjeID");

                    b.Property<int>("BirimKoordinatoruID");

                    b.HasKey("ProjeID", "BirimKoordinatoruID");

                    b.HasIndex("BirimKoordinatoruID");

                    b.ToTable("ProjeBirim");
                });

            modelBuilder.Entity("StajyerTakip.Models.Stajyer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bolum");

                    b.Property<int>("ModeratorID");

                    b.Property<string>("Okul");

                    b.Property<int>("ProfilID");

                    b.HasKey("ID");

                    b.HasIndex("ModeratorID");

                    b.HasIndex("ProfilID");

                    b.ToTable("Stajyerler");
                });

            modelBuilder.Entity("StajyerTakip.Models.StajyerBirimK", b =>
                {
                    b.Property<int>("StajyerID");

                    b.Property<int>("BirimKID");

                    b.HasKey("StajyerID", "BirimKID");

                    b.HasIndex("BirimKID");

                    b.ToTable("StajyerBirimK");
                });

            modelBuilder.Entity("StajyerTakip.Models.StajyerProje", b =>
                {
                    b.Property<int>("StajyerID");

                    b.Property<int>("ProjeID");

                    b.HasKey("StajyerID", "ProjeID");

                    b.HasIndex("ProjeID");

                    b.ToTable("StajyerProje");
                });

            modelBuilder.Entity("StajyerTakip.Models.BirimKoordinatoru", b =>
                {
                    b.HasOne("StajyerTakip.Models.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StajyerTakip.Models.Moderator", "Moderator")
                        .WithMany("BirimKoordinatorleri")
                        .HasForeignKey("ModeratorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StajyerTakip.Models.Profil", "Profil")
                        .WithMany()
                        .HasForeignKey("ProfilID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StajyerTakip.Models.Devamsizlik", b =>
                {
                    b.HasOne("StajyerTakip.Models.BirimKoordinatoru")
                        .WithMany("Devamsizliklar")
                        .HasForeignKey("BirimKoordinatoruID");

                    b.HasOne("StajyerTakip.Models.Stajyer", "Stajyer")
                        .WithMany("Devamsizliklar")
                        .HasForeignKey("StajyerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StajyerTakip.Models.EkDosya", b =>
                {
                    b.HasOne("StajyerTakip.Models.Gunluk", "Gunluk")
                        .WithMany("Ekler")
                        .HasForeignKey("GunlukID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StajyerTakip.Models.Gunluk", b =>
                {
                    b.HasOne("StajyerTakip.Models.BirimKoordinatoru")
                        .WithMany("Gunlukler")
                        .HasForeignKey("BirimKoordinatoruID");

                    b.HasOne("StajyerTakip.Models.Stajyer", "Ogrenci")
                        .WithMany("Gunlukler")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StajyerTakip.Models.Moderator", b =>
                {
                    b.HasOne("StajyerTakip.Models.Profil", "Profil")
                        .WithMany()
                        .HasForeignKey("ProfilID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StajyerTakip.Models.ProjeBirim", b =>
                {
                    b.HasOne("StajyerTakip.Models.BirimKoordinatoru", "BirimKoordinatoru")
                        .WithMany("Projeler")
                        .HasForeignKey("BirimKoordinatoruID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StajyerTakip.Models.Proje", "Proje")
                        .WithMany("BirimKoordinatorleri")
                        .HasForeignKey("ProjeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StajyerTakip.Models.Stajyer", b =>
                {
                    b.HasOne("StajyerTakip.Models.Moderator", "Moderator")
                        .WithMany("Stajyerler")
                        .HasForeignKey("ModeratorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StajyerTakip.Models.Profil", "Profil")
                        .WithMany()
                        .HasForeignKey("ProfilID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StajyerTakip.Models.StajyerBirimK", b =>
                {
                    b.HasOne("StajyerTakip.Models.BirimKoordinatoru", "BirimK")
                        .WithMany("Stajyerler")
                        .HasForeignKey("BirimKID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StajyerTakip.Models.Stajyer", "Stajyer")
                        .WithMany("BirimKoordinatorleri")
                        .HasForeignKey("StajyerID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StajyerTakip.Models.StajyerProje", b =>
                {
                    b.HasOne("StajyerTakip.Models.Proje", "Proje")
                        .WithMany("Stajyerler")
                        .HasForeignKey("ProjeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StajyerTakip.Models.Stajyer", "Stajyer")
                        .WithMany("Projeler")
                        .HasForeignKey("StajyerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
